#### Création
#POST http://localhost:8081/user_api
#Accept: application/json
#Content-Type: application/json
#
#{
#  "email":"toto@toto.toto",
#  "password":"toto"
#}
#
#### Création
#POST http://localhost:8081/user_api
#Accept: application/json
#Content-Type: application/json
#
#{
#  "email":"titi@titi.titi",
#  "password":"titi"
#}
#
#### Création
#POST http://localhost:8081/user_api
#Accept: application/json
#Content-Type: application/json
#
#{
#  "email":"tutu@tutu.tutu",
#  "password":"tutu"
#}
####

POST http://localhost:8081/user_api/check
Accept: application/json
Content-Type: application/json

{
  "id":"0e8084c8-1ddf-4b07-abb6-556964822cad",
  "email":"toto@toto.toto",
  "password":"toto"
}

###
POST http://localhost:8081/user_api/check
Accept: application/json
Content-Type: application/json

{
  "email":"toto@toto.toto",
  "password":"toto"
}

###
PUT http://localhost:8081/user_api
Accept: application/json
Content-Type: application/json
X-UserId: 0e8084c8-1ddf-4b07-abb6-556964822cad

{
  "id":"0e8084c8-1ddf-4b07-abb6-556964822cad",
  "email":"toto@toto.toto",
  "password":"topito"
}
###
PUT http://localhost:8081/user_api
Accept: application/json
Content-Type: application/json

{
  "email":"toto@toto.toto",
  "password":"topitota"
}

###
POST http://localhost:8081/user_api/check
Accept: application/json
Content-Type: application/json

{
  "email": "tutu@tutu.tutu",
  "password": "tutu"
}